- en/option/series/pie.md
central angle issue as PR https://github.com/ecomfe/echarts-doc/pull/13
> central angle

- cn/option/partial/mark-point.md
- en/option/partial/mark-point.md
> fix: correct default value for markpoint label

- en/option/series/bar.md
Changes all instances of bodrder to border inside the bar series type
> Fix bar series border typos

- en/option/series/line.md
Hi!
The proposed changes of this pull request can be extended to more options, I did the smallest thing possible to show how the writing style would look, this type of writing is inspired from the vue docs, e.g. https://vuejs.org/v2/api/#productionTip . If the maintainers of the project agree, I can do these in multiple pull requests as to help provide a little bit more context of what the boolean options do.
Please let me know if this okay, if not please feel free to close this pull request
Thanks!
> Change wording of boolean options

- en/option/component/calendar.md
Another follow up from #38, please let me know if there's anything you would like me to change
> Change calendar boolean props wording

- en/option/component/axis-common.md
- en/option/component/x-axis.md
- en/option/component/y-axis.md
Another pull request that follows the work from #38
> Change axis boolean options wording

- en/option/component/title.md
This pull requests continues the work from: https://github.com/ecomfe/echarts-doc/pull/38
This is for the component options, I'll be creating multiple branches for the different API options
> Change component options boolean props wording

- en/tutorial/getting-started.md
- Since we are asking the user to pick from a list of methods, I've changed it from a number list to an unordered list
- Also improved some language to make it clearer to understand
> Improve getting started page

- cn/option/partial/text-style.md
- en/option/partial/text-style.md
Hi @Ovilia here is doc for https://github.com/apache/incubator-echarts/pull/10487
> Label color support function

- cn/option/series/pie.md
- en/option/series/pie.md
feat: doc for pie-series.animationTypeUpdate apache/incubator-echarts#11029
> feat: doc for pie-series.animationTypeUpdate

- en/option/component/title.md
- zh/option/component/title.md
> Fix wrong description in title

- en/option/component/geo-common.md
related PR https://github.com/apache/incubator-echarts/pull/12156
> add new option 'nameProperty' in map series option

- en/option/series/gauge.md
- zh/option/series/gauge.md
Add gauge.detail.formatter option
> add missing option for gauge

- en/option/partial/tooltip-common.md
- zh/option/partial/tooltip-common.md
> 修改文档书写错误issue#97

- en/option/partial/symbol.md
- en/option/series/effectScatter.md
- zh/option/partial/symbol.md
- zh/option/series/effectScatter.md
Related to https://github.com/apache/incubator-echarts/pull/12348.
> feat: added function type for `symbolRotate`

- en/tutorial/dataset.md
- en/tutorial/style-overview.md
> fix en doc

- en/api/echarts.md
- en/api/events.md
- en/option/partial/2d-data.md
- en/option/series/custom.md
- en/tutorial/custom-series.md
- zh/api/echarts.md
- zh/api/events.md
- zh/option/partial/2d-data.md
- zh/option/series/custom.md
- zh/tutorial/custom-series.md
Fixed some incorrect links in present document.
> fix: fixed some link errors.

- en/option/series/sankey.md
changes to sankey supporting typing changes in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45354
see discussion also in https://github.com/apache/incubator-echarts/issues/12763
> add name, nodeAlign to sankey

- en/option/component/radar.md
- zh/option/component/radar.md
textStyle is missing in rada.name
> Add textStyle to radar.name

- en/api/echarts.md
- zh/api/echarts.md
Add missing colon in echarts.md
> Add missing colon

- en/option/partial/gauge-title-detail.md
- en/option/partial/roundCap.md
- en/option/partial/text-style.md
- en/option/series/bar.md
- en/option/series/gauge.md
- zh/option/partial/gauge-title-detail.md
- zh/option/partial/roundCap.md
- zh/option/partial/text-style.md
- zh/option/series/bar.md
- zh/option/series/gauge.md
|configuration|before|after|
|--|--|--|
|axisLine.lineStyle.color|`[[0.2, '#91c7ae'], [0.8, '#63869e'], [1, '#c23531']]`|`[[1, '#E6EBF8']]`|
|axisLine.lineStyle.width|30|10|
|axisLine.roundCap|-|false|
|splitLine.length|30|10|
|splitLine.lineStyle.color|'#eee'|'#63677A'|
|splitLine.lineStyle.width|2|3|
|axisTick.length|8|6|
|axisTick.lineStyle.color|'#eee'|'#63677A'|
|axisLabel.distance|5|15|
|axisLabel.color|'auto'|'#46464'|
|axisLabel.fontSize|-|12|
|pointer.icon|-|null/svg/img/rect/...|
|pointer.offsetCenter|-|[0,0]|
|poinet.length|'80%'|'60%'|
|pointer.width|8|6|
|poiner.keepAspect|-|false|
|title.color|'#333'|'#464646'|
|title.offserCenter|[0, '-40%']|[0, '20%']|
|title.fontSzie|15|16|
|detail.color|'auto'|'#464646'|
|detail.fontWeight|-|'bold'|
|detail.lineHeight|-|30| …
> add content of gauge

- en/changelog.md
fix some typos and broken links for examples in commit: https://github.com/apache/incubator-echarts-doc/commit/0d3d2187c86ef832f9b795615777603a50fe8207
> fix(changelog): fix some typos and broken links for examples.

- en/option/partial/tooltip-common.md
- zh/option/partial/tooltip-common.md
> Fix(tooltip): fix wrong props

- en/tutorial/style-overview.md
- zh/tutorial/style-overview.md
> Modify the wrong URL of theme builder.

- en/tutorial/npm-webpack.md
- zh/tutorial/npm-webpack.md
Update `Available modules` file location
> Fix(#142): update export modules file

- en/api/echarts-instance.md
- zh/api/echarts-instance.md
- add fontFamily/fontWeight/fontStyle to showLoading
> feature(loading) support fontFamily/fontWeight/fontStyle

- en/tutorial/styling.md
- zh/tutorial/styling.md
`[visualMap](~option.html#visualMap)' => '[visualMap](option.html#visualMap)`
> fix(tutorial): fix visualMap linking error

- en/option/series/graph.md
- zh/option/series/graph.md
fix the autoCurveness type, add boolean type and default value.
> add(graph):fix auto curveness doc

- en/option/component/legend.md
- en/option/partial/item-style.md
- en/option/partial/line-border-style.md
- en/option/partial/line-style.md
- zh/option/component/legend.md
- zh/option/partial/item-style.md
- zh/option/partial/line-border-style.md
- zh/option/partial/line-style.md
more intuitive legend apache/echarts#14497
> doc: more intuitive legend apache/echarts#14497

- en/option/series/gauge.md
- zh/option/series/gauge.md
> fix(gauge): some distances should be able to be set to negative numbers

- en/option/series/pie.md
- zh/option/series/pie.md
fix(pie): remove align and verticalAlign in pie label apache/echarts#15771
> fix(pie): remove align and verticalAlign in pie label apache/echarts#15771

- en/option/series/sankey.md
> fix(sankey): fix spelling error

- .github/workflows/nodejs.yml
- en/option/partial/label-layout.md
- en/option/partial/text-style.md
- zh/option/partial/label-layout.md
- zh/option/partial/text-style.md
and update ci config so that is can be run on each pr.
> fix: remove lineOverflow because this param is not exposed in echarts

- en/option/component/visual-map-continuous.md
- zh/option/component/visual-map-continuous.md
> Fix ture -> true

- en/option/series/bar.md
- zh/option/series/bar.md
from [this issue](https://github.com/apache/echarts/issues/15591) , add mark to series.bar.
> doc: quote mark in series.bar

- en/option/partial/zr-graphic.md
- zh/option/partial/zr-graphic.md
For [apace/echarts#16513](https://github.com/apache/echarts/pull/16513#:~:text=one%20when%20merging.-,Other%20information,-Group%20doesn%27t%20support)
> fix(graphic): remove unsupported options from graphic `group`. 

- en/option/series/heatmap.md
- zh/option/series/heatmap.md
refer to [issue 16493](https://github.com/apache/echarts/pull/16493)
> docs: series.heatmap itemStyle.borderRadius

- en/option/component/toolbox.md
Replace old URI `http://echarts.baidu.com/images/favicon.png` -> `https://echarts.apache.org/en/images/favicon.png`.
> Update toolbox.md icon

- zh/option/component/visual-map-piecewise.md
Resolve https://github.com/apache/echarts/issues/16706
> fix:  Update visualMap.textGap in ch/visual-map-piecewise.md

- en/option/series/line.md
- en/option/series/radar.md
- zh/option/series/line.md
- zh/option/series/radar.md
- Close https://github.com/apache/echarts/issues/16779
> fix(areaStyle.opacity): line areaStyle default opacity is 0.7

- en/option/partial/formatter.md
To synchronize the English document for `formatter` as it seems to be not being kept updated with the Chinese document.
> fix(formatter): sync en formatter doc from zh

- en/option/partial/emphasis-common.md
- en/option/series/tree.md
- zh/option/partial/emphasis-common.md
- zh/option/series/tree.md
- https://github.com/apache/echarts/pull/17009
> feat(tree): add `relative` for `tree.emphasis.focus`

- zh/option/component/visual-map-continuous.md
~ExampleUIControVector~
ExampleUIControlVector
> docs(visual-map-continuous): fix spelling error

- en/option/series/treemap.md
- zh/option/series/treemap.md
- https://github.com/apache/echarts/pull/17242
> feat(treemap.breadcrumb.emphasis): add version

- en/option/partial/label-rotate-tangential.md
- en/option/series/gauge.md
- en/option/series/sunburst.md
- zh/option/partial/label-rotate-tangential.md
- zh/option/series/gauge.md
- zh/option/series/sunburst.md
> doc(gauge): axisLabel support rotate apache/echarts#16985

- en/option/component/data-zoom.md
- zh/option/component/data-zoom.md
Modify typos fiterMode->filterMode
> Modify typos fiterMode->filterMode

- en/option/series/sankey.md
- zh/option/series/sankey.md
- https://github.com/apache/echarts/pull/16767
> feat(sankey): add doc for sankey `edgeLabel`

- en/option/series/graph.md
- zh/option/series/graph.md
Reverts apache/echarts-doc#197
> Revert "docs: update graph draggable option"

- en/option/series/candlestick.md
- zh/option/series/candlestick.md
feat(candlestick): add doc for borderColorDoji apache/echarts#17717
> feat(candlestick): add doc for borderColorDoji apache/echarts#17717

- en/option/series/sunburst.md
- zh/option/series/sunburst.md
Add `startAngle` for `sunbrust`
- relate to https://github.com/apache/echarts/pull/18240
> fix(sunburst): add `startAngle`

- en/option/partial/emphasis-common.md
- en/option/series/sankey.md
> feat(sankey): add new strategy `trajectory` for emphasis focus of sankey

- en/option/partial/zr-graphic.md
- zh/option/partial/zr-graphic.md
add doc for `style.width`, `style.overflow`, `style.ellipsis`
https://echarts.apache.org/examples/zh/editor.html?c=line-graphic&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzJrqwECGYlJA2gOQCCGkYArgVrABQDWAWwCUsAG4BnWABUsAkFgBO1dgu48ADQGEhDALpkAvgBoyYYMFYQQJVOVhgFEHHgUkGlAB4RxDE3YBmwAoC1GCKbjJyisqqsCQAPABGCgD0AHxIiQaCccgAxgZaDIZ-sDiOxKR22P5gbgDMAKS-ZOiOOAAWdbAMACzNpeiJwGBmAg0DrbB5MDQQ0AAylIlYGCQO7FglZB5MXuI2U2AAnvJuopQYmy12nt5LK2tVdrCBwaHhPUgXV1gGsEUpgZtuhjntvIc7Cczj08tRcEFjjdyHdxAt5lgbLAYAAtRTAEj-S7ibjGKaoh6rSEvN4hUafBjfS6bf6CYp2Ml2YbsQiUBTHADilGs9gUm0GFGotFgjAADL4egBGeVGHoAJhVPXqmr6OoArDqAGw6gDsOoAHPL9OhOWUlCAOhA8vQprYXtDMT1ysB2CBkXYFCNqFBoCQALLUDoAOgACgBJWApWC9CVDH2EeY4NxKADu_vI7S6JEVytTsGGo2A41gJdlZYAXsXZXWpug8o6MARVKGZa3yG6XuQPdmsHkwPnBzVugw8vgwgoJ-7QG5Z9B54u7I2a82y3ZxB1hZ6B4PyDmIAQwB0SL0d33B …
> doc(graphic-text): add doc for `style.width`, `style.overflow`, `style.ellipsis`

- en/option/partial/axisPointer-common.md
- zh/option/partial/axisPointer-common.md
This documentation change goes with https://github.com/apache/echarts/pull/18524. 
One of my teammates helped me with the Chinese translation, but wasn't 100% sure about translating a couple of the more technical terms. Please let me know if you want anything changed.
> doc(axisPointer): document `triggerEmphasis` option

- en/changelog.md
- zh/changelog.md
> release echarts v5.4.3

- en/option/series/pie.md
- zh/option/series/pie.md
related echart pr https://github.com/apache/echarts/pull/19076
> feat(pie): add padAngle doc description

- en/option/component/matrix.md
- en/option/option.md
- en/option/partial/matrix-header.md
- zh/option/component/matrix.md
- zh/option/option.md
- zh/option/partial/matrix-header.md
add doc for apache/echarts#19807
> doc(matrix): add doc for apache/echarts#19807

- zh/option/partial/2d-data.md
> fix typo in 2d-data.md

- en/option/partial/selected-mode.md
Modify selectedMode English document
> fix(doc): Modify selectedMode EN doc

- en/option/component/aria.md
- zh/option/component/aria.md
pr: https://github.com/apache/echarts/pull/20218
> docs: exclude column indexes from aria-label

- en/option-gl/component/axis3D-axis-common.md
- en/option/component/axis-common.md
https://github.com/apache/echarts/issues/17576
> Interval is unavailable on time axis

- en/option/series/sunburst.md
- zh/option/series/sunburst.md
docs for https://github.com/apache/echarts/pull/20399
> docs(sunburst): add new emphasis focus strategy 'relative'

- en/option/partial/universal-transition.md
- en/option/partial/zr-graphic.md
- zh/option/partial/universal-transition.md
- zh/option/partial/zr-graphic.md
Fix typo in universal-transition.md and zr-graphic.md
> Fix typo in universal-transition.md and zr-graphic.md
