cn/tutorial/getting-started.md
en/tutorial/getting-started.md

Follow the spec:
https://www.w3.org/TR/html5/document-metadata.html#the-head-element
> #### 4.2.5 The meta element:
> **Contexts in which this element can be used:**
> If the charset attribute is present, or if the element's http-equiv attribute is in the encoding declaration state: in a head element.

The <meta> element here should go inside the <head> element, but not the <header>.

---

cn/option-gl/partial/icon.md
cn/option/partial/icon.md
en/option/partial/icon.md

This PR adds the `none` icon type to the list of icon types present on the series[i]-line. symbol documentation. The use of the `none` icon type has the following result:

Add missing icon type on series[i]-line. symbol

---

en/option/component/axis-common.md

The default value is 'end' instead of 'start'

fix: correct the default value of axis nameLocation in Engligh docs

---

en/option/partial/axisPointer-common.md

Fixes a missing space from the axisPointer-common => show description

Fix missing space from xAxis.axisPointer description

---

en/option/partial/mark-point.md

-fix yAxis typo in mark-point parameters: change all instances of yAixs to yAxis

Fix yAxis typo in markPoint Option docs

---

en/option/component/toolbox.md

I noticed that inside the `features` API option of the toolbox component, the titles for each of the default toolbox features had `boolean` as the default data type instead of the intended `string`

change title data type from boolean to string in the toolbox component

---

en/option/component/visual-map-piecewise.md
en/option/partial/z-zlevel.md

Fixes a few typos in `visual-map-piecewise` and `z-level`

fixes typos

---

en/option/component/visual-map-piecewise.md

- small typo found here: https://echarts.apache.org/en/option.html#visualMap-piecewise.categories
- previously: "...from dataVale to visual channels"

visualMap piecewise.categories dataValue typo correction

---

en/option/component/dataset.md

- broken link found in [dataset options docs](https://echarts.apache.org/en/option.html#dataset)
- new link: https://echarts.apache.org/en/tutorial.html#Dataset
- old link: https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#dataset

fix broken tutorial link in dataset options

---

en/option/component/polar.md
en/option/series/bar.md
zh/option/component/polar.md
zh/option/series/bar.md

add doc for polar roundCap apache/incubator-echarts#11393

add doc for polar roundCap apache/incubator-echarts#11393

---

en/option/partial/mark-point.md
en/option/partial/marker.md
en/option/series/bar.md
en/option/series/boxplot.md
en/option/series/candlestick.md
en/option/series/effectScatter.md
en/option/series/funnel.md
en/option/series/gauge.md
en/option/series/graph.md
en/option/series/heatmap.md
en/option/series/line.md
en/option/series/lines.md
en/option/series/map.md
en/option/series/pictorialBar.md
en/option/series/pie.md
en/option/series/radar.md
en/option/series/scatter.md
en/option/series/tree.md
zh/option/partial/mark-point.md
zh/option/partial/marker.md
zh/option/series/effectScatter.md

Some series are missing the `name` or `seriesType` property which brings a unexpected document description or a bad link.

fix: added missing properties(name/seriesType) in some series.

---

en/api/action.md
en/api/events.md
zh/api/action.md
zh/api/events.md

Currently, events(`legendselectall` & `legendinverseselect`) and actions(`legendAllSelect` & `legendInverseSelect`) are missing in `legend` component.
Added them according to https://github.com/apache/incubator-echarts/blob/master/src/component/legend/legendAction.js#L82-L90

feat: added missing events and actions docs of legend(selectall & inverseselect).

---

en/option/series/gauge.md

Original Mail: https://lists.apache.org/thread.html/racf2a880dbdacbe85d6791f6c35e753a796c1ff3f0f1066769583d14%40%3Cdev.echarts.apache.org%3E

fix: added missing option `axisLabel.distance` for Gauge series.

---

zh/option/series/sankey.md

Related to #107.
Thanks to @softwords, he added the missing options (`name` & `nodeAlign`) into English document.
I found that [`nodeAlign`](https://echarts.apache.org/zh/option.html#series-sankey.nodeAlign) exsits but `name` is also missing in Chinese document, so I've created this PR to add it.

fix(sankey): added missing `name` option.

---

zh/option/component/axis-common.md

Chinese document shouldn't display the English translation.
- https://echarts.apache.org/zh/option.html#xAxis.axisPointer
- https://echarts.apache.org/zh/option.html#yAxis.axisPointer

fix(axisPointer): change en to zh.

---

en/option/series/gauge.md
zh/option/series/gauge.md

Added missing buttons in gauge examples.
- https://echarts.apache.org/zh/option.html#series-gauge
- https://echarts.apache.org/en/option.html#series-gauge
Before
After

fix(gauge): added missing buttons in gauge example.

---

en/api/echarts-instance.md
en/option/component/toolbox.md
en/option/component/visual-map-piecewise.md
en/option/component/visual-map.md
slides/ani/asset/common/echarts.min.js
slides/arch-brief/asset/common/echarts.min.js
slides/custom/asset/common/echarts.js
zh/option/component/toolbox.md

This replaces a typo in the documentation, which sometimes lists "defualt" instead of default.
It's nothing major, really - just something i noticed while reading through the docs.
https://github.com/apache/incubator-echarts/pull/12828 does the same for code-comments.

Replace defualt with default (fixing typo)

---

en/option/series/gauge.md
zh/option/series/gauge.md

fix(gauge): added missing colon in option of Gauge Series, which leads the losing of `legendHoverLink`.

---

zh/option/option.md

For Chinese documentation, the link about [`blendMode`](https://echarts.apache.org/zh/option.html#blendMode)
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation 
should be replaced with 
https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

fix: blendMode link uses zh-CN but not en-US in Chinese documentation.

---

en/option/series/themeRiver.md
zh/option/series/themeRiver.md

See comments here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45354
themeriver is the last series that requires `name` to be added. Creating this link in documentation means it can be referred to from `index.d.ts`

fix(themeRiver): add 'name'

---

src/components/DocContent.vue
tool/md2json.js

- Don't show live example button and component if the doc is not the type of option and gl-option.
- Don't parse UI component if the doc is the type of option or gl-option.

tweak: show live example button and component only when doc is type of option/gl-option.

---

en/option-gl/partial/shading.md
en/option-gl/partial/temporal-super-sampling.md
src/components/DocContent.vue
src/components/LiveExample.vue
src/i18n.js
src/store.js

- Added support for changing the layout of the option example preview panel.
The valid value of layout can be `top`, `bottom`, `right` and `auto`.
By default, if the user never sets the layout manually, `auto` will be used. `auto` means that the panel will be at the bottom when the width of window is less than 1400px and otherwise it will be at the right.
And the browser will remember the layout settings by `localStorage` so that the user can continue to use the preferred layout later.
- Fixed some error links.

feat: added support for changing the layout of option example preview panel.

---

src/components/DocContent.vue

Currently, when the layout of live example panel is `top` or `bottom`, using the margin with a percent value for doc content dom is not a bit suitable, since it's based on the width of parent element.
Here I'm trying to set manually the margin value of the doc content according to its real width or height when the path or window's size changed.
**Before**
**After**

tweak: tweak live example layout style.

---

src/components/Search.vue

The current search result‘s width minimum is 300px (same as before), and the maximum is the maximum width of the current result.

fix: search result width

---

src/components/LiveExample.vue

Such as `DataView`.
**Before**
**After**

fix(live-preview): add `position: relative` to make its child DOM elements with absolute positioning layout correctly.

---

en/option/component/radar.md
zh/option/component/radar.md

This issue had reported by #131, but that seems to be not working.
According to the code in this line https://github.com/apache/incubator-echarts/blob/next/src/coord/radar/RadarModel.ts#L105,
maybe we need to remove the current `textStyle` node.
**Current**
**After**

fix(radar): fix textStyle does not work bug.

---

en/tutorial/renderer.md

When reading the documentation on Canvas vs SVG, I noticed a few typos I felt worthwhile fixing.

fix typos and improve grammar on renderer section

---

en/option/partial/data-transform.md
en/tutorial/dataset.md
zh/option/partial/data-transform.md
zh/tutorial/dataset.md

fix typo in dataset & data-transform docs:
- `datat set` -> `data set`

fix: typo in dataset & data-transform

---

zh/option/component/data-zoom-inside.md

Original issue was https://github.com/apache/echarts/issues/14018
and `zoomLock` on [dataZoom-inside.zoomLock ](https://echarts.apache.org/next/zh/option.html#dataZoom-inside.zoomLock) not work as expect since one of `dataZoom` array item is missing `zoomLock`

chore: make dataZoom example simpler

---

tool/md2json.js

Like apache/incubator-echarts#13629, `globby` does not support `'\'` yet.
It can't scan files if the path pattern contains `'\'` in Windows.
So `npm run watch` cannot run.
```js
TypeError: etplEngine.getRenderer(...) is not a function
at convert (C:\echarts\echarts-doc\tool\md2json.js:57:46)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)\
```
In the meanwhile, please help to check if it works well in macOS.
Thanks!

fix(tool): fix a compatibility issue of `globby` in Windows.

---

en/tutorial/tree-shaking.md
zh/tutorial/tree-shaking.md

There is a little typo in English version of typescript tree-shaking code.
And I added several lines of code of typecript tree-shaking for a clear guidance.

fix: modify typescript tree-shaking tutorial code

---

en/option/partial/item-style.md
en/option/partial/line-border-style.md
en/option/partial/line-style.md
en/option/partial/text-style.md
zh/option/partial/item-style.md
zh/option/partial/line-border-style.md
zh/option/partial/line-style.md
zh/option/partial/text-style.md

Added documents for some newly added border options.
- new acceptable value types for `type` _**number | number[]**_
- cap
- join
- dashOffset
- miterLimit
- new acceptable value types of `borderType` _**number | number[]**_
- borderCap
- borderJoin
- borderDashOffset
- borderMiterLimit
- new acceptable value types of `borderType` _**number | number[]**_
- borderDashOffset
- new acceptable value types of `textBorderType` _**number | number[]**_
- textBorderDashOffset

feat(border): add new border options brought by v5.

---

en/api/echarts.md
zh/api/echarts.md

1. Add `useDirtyRect` feature in API doc.
2. Add a notice that when calling `echarts.init` with `opts`, a `null` should also be passed if no need to specify a theme.
3. Add a reference link for `theme` in echarts.init().

Add `useDirtyRect` feature in API doc and etc

---

en/option/component/axis-common.md

I noticed one of the examples uses the wrong parameter name: `idx` instead of `index`.
This example function is correct in the [zh translation](https://github.com/apache/echarts-doc/blob/master/zh/option/component/axis-common.md).
Thanks for this lib and its awesome documentation!

fix(axisLabel.formatter): example variable name

---

zh/option/series/graph.md

`graph.label.formatter` was missing from the doc.

fix(graph): fix graph label formatter apache/echarts#14780

---

en/option/series/sankey.md
zh/option/series/sankey.md

Move `sankey.lineStyle.color`  to more appropriate place.

chore: refine sankey line style color

---

en/option/component/radar.md
zh/option/component/radar.md

According to [compatStyle.ts#L295](https://github.com/apache/echarts/blob/c2cdc02d6f5f2436104061f97236b4f182625231/src/preprocessor/helper/compatStyle.ts#L295), `radar.name` is deprecated and should use `radar.axisName` instead. 
Tested and confirmed that either of the options works.

fix(radar): radar.name is deprecated

---

en/option/component/calendar.md
zh/option/component/calendar.md

fix(calendar): improve the calendar `nameMap` document

---

en/option/partial/label.md
en/option/partial/text-style.md
en/option/series/treemap.md
zh/option/partial/label.md
zh/option/partial/text-style.md
zh/option/series/treemap.md

The default value of `series-treemap.label.padding` should be `5` according to [TreemapSeries.ts](https://github.com/apache/echarts/blob/6d68a7dadbd73ff79831d819e014e859f8b2241a/src/chart/treemap/TreemapSeries.ts#L275) but it's `0` in the current doc.

fix: dafault value of treemap.label.padding

---

en/option/series/pictorialBar.md
zh/option/series/pictorialBar.md

~~`pictoialBar`~~
`pictorialBar`

doc(pictorialBar): fix spelling error

---

en/option/partial/axisPointer-common.md
zh/option/partial/axisPointer-common.md

- Only change `.md` docs.
- Seems like a long-existing tiny typo.

fix(axisPointer): typo of `margin` type

---

en/api/echarts-instance.md
en/tutorial/event.md
zh/api/echarts-instance.md
zh/tutorial/event.md

Since add an event for `dataZoom` has limited interest,  so we should remove in doc so user wouldn't be confused.
- Close https://github.com/apache/echarts/issues/15775

chore: remove event example for `dataZoom`

---

en/option-gl/partial/viewport.md
en/option/partial/rect-layout.md

Fixes small typo in option and option-gl docs(changed value from `left` to `top` for top sections).

docs: fix typo in option and option-gl docs

---

en/option/component/data-zoom-slider.md
zh/option/component/data-zoom-slider.md

According to source code, we could set size of dataZoom-slider.
https://github.com/apache/echarts/blob/4a8a7f58e772586eebfbb080d2d14f5ded5478c0/src/component/dataZoom/SliderZoomView.ts#L245

docs: add size option for dataZoom-slider

---

en/option/series/treemap.md
zh/option/series/treemap.md

As is discussed in https://github.com/apache/echarts/pull/16760, `colorAlpha` should be removed because 
- A [bug](https://github.com/apache/echarts/issues/16749) is preventing this api to work properly and fixing it with [my PR](https://github.com/apache/echarts/pull/16760) will introduce **great workload** and **complexity**. 
- Developers can set opacity easily in `color` option with **rgba format**, so `colorAlpha` might not be needed anymore.
Removal of `colorAlpha` in source code will be implemented in following PRs at Echarts.

fix: Removing colorAlpha for bug existence and low priority

---

en/option/partial/formatter.md

PR fixes the code block for the formatter `params` example so that it's now properly closed. Currently, because it's not properly closed, and so is messing up the HTML following it. An example of this is https://echarts.apache.org/en/option.html#tooltip.formatter.

Fix params example for formatter code block

---

en/option/partial/icon.md

PR adds `square` as an allowed builtin icon. I was looking at https://echarts.apache.org/en/option.html#legend.icon and it did not show `square`, though it does work, which was confusing to me.

Add square as allowed builtin icon

---

en/option-gl/series/bar3D.md
en/option/series/bar.md
en/option/series/line.md
zh/option/series/bar.md
zh/option/series/line.md

Docs for the `stackStrategy` feature proposed in https://github.com/apache/echarts/pull/17086

feat: add stackStrategy docs

---

en/option/partial/axisPointer-common.md
en/tutorial/renderer.md

Fixing two typos. ('initail' => 'initial')

fix: typo of "initial"

---

en/api/events.md
zh/api/events.md

Many developers have asked how to listen to roaming events and I found this part of document is missing.

doc: add doc for graphroam, georoam, and treeroam

---

en/option/partial/coord-sys.md
en/option/series/boxplot.md
en/option/series/candlestick.md
en/option/series/effectScatter.md
en/option/series/line.md
en/option/series/pie.md
en/option/series/scatter.md
en/option/series/themeRiver.md
zh/option/partial/coord-sys.md
zh/option/series/boxplot.md
zh/option/series/candlestick.md
zh/option/series/effectScatter.md
zh/option/series/line.md
zh/option/series/pie.md
zh/option/series/scatter.md

For apache/echarts#17132. Also fixed some wrong `seriesType` passed to the `coord-sys` partial component. I don't mention the `cartesian2d` coordinate as it's not supported perfectly.

feat(pie): add docs for new option `coordinateSystem` of the pie series

---

en/option/partial/encode-dimensions.md
en/option/partial/group-id.md
en/option/partial/universal-transition.md
en/option/series/bar.md
en/option/series/boxplot.md
en/option/series/candlestick.md
en/option/series/custom.md
en/option/series/heatmap.md
en/option/series/line.md
en/option/series/lines.md
en/option/series/map.md
en/option/series/pictorialBar.md
en/option/series/pie.md
en/option/series/radar.md
en/option/series/scatter.md
zh/option/partial/encode-dimensions.md
zh/option/partial/group-id.md
zh/option/partial/universal-transition.md
zh/option/series/bar.md
zh/option/series/boxplot.md
zh/option/series/candlestick.md
zh/option/series/custom.md
zh/option/series/heatmap.md
zh/option/series/line.md
zh/option/series/lines.md
zh/option/series/map.md
zh/option/series/pictorialBar.md
zh/option/series/pie.md
zh/option/series/radar.md
zh/option/series/scatter.md

modified:
- series.dataGroupId
- series.data.groupId
- series.data.childGroupId (Add)
- series.encode
- series.universalTransition

docs: update documents for multiple level drilldown - `childGroupId`

---

en/option/component/geo.md

small typo under geo.md: 
from coorinate to coordinate
Source: https://en.wikipedia.org/wiki/Coordinate_(disambiguation)

fix typo in geo.md

---

en/option/series/graph.md
zh/option/series/graph.md

Update docs for PR https://github.com/apache/echarts/pull/15428

docs: update graph draggable option

---

en/option/partial/encode-dimensions.md
en/option/partial/group-id.md
zh/option/partial/encode-dimensions.md
zh/option/partial/group-id.md

reference: https://github.com/apache/echarts-doc/pull/295#discussion_r1038745524
Hi @plainheart, please review this PR. In this PR, I added a version tip for `childGroupId` and a version comment for `encode.itemChildGroupId`. Also, I fixed the inconsistent link to multi-drilldown example.

chore(group-id): add version tip and fix inconsistent example link

---

en/option/partial/tooltip-common.md

related echarts pr: [apache/echarts#19123](https://github.com/apache/echarts/pull/19123)

feat(tooltip): add dataIndex to valueFormatter callback

---

en/option/partial/item-style.md
en/option/series/sankey.md
zh/option/partial/item-style.md
zh/option/series/sankey.md

Relates to https://github.com/apache/echarts/pull/19763

doc(sankey): add doc for sankey itemStyle.borderRadius

---

en/option/partial/barGrid.md
zh/option/partial/barGrid.md

According to this problem, it was found that there is a discrepancy between the document and the actual situation.
[Bug] Default value of `barCategoryGap` and `barGap` not as described in the document apache/echarts#20148
There is a discrepancy between the documentation and the code. When setting `barGap`, the default value should be 20% instead of 30%. The specific change results are as shown in the figure.
The default value of `barCategoryGap` is a value calculated based on the number of bar series. Relevant instructions should be added to the document. As shown in the figure

fix(barGrid):Modify the default value of the barGap attribute and the default value of the barCategoryGap attribute 

---

en/option/component/axis-common.md
zh/option/component/axis-common.md

Add feature showMinLine showMaxLine to splitline in coordinate axis.
User can set the showMinLine/ showMaxLine be false to delete the first/last split line.

feature(axis): Add showMinLine and showMaxLine to splitLine

---

en/changelog.md

fix(doc): `dimension` typo

---

en/tutorial/echarts-feature.md

There seems to be a discrepancy between the `echarts-feature.md` file on this repo and [the one online](https://echarts.apache.org/en/feature.html), but I have edited here regardless. Currently, it reads very awkwardly and so I have
- Fixed grammar and spelling
- Restructured some sections
- Removed redundant sentences
- Make the title case be consistent
Hopefully this is helpful.

Grammar and spelling improvements for feature page

---

en/option/series/bar.md
en/option/series/line.md
zh/option/series/bar.md
zh/option/series/line.md

https://github.com/apache/echarts/pull/20998

doc: add doc for stackOrder

---

en/api/echarts-instance.md
zh/api/echarts-instance.md

https://github.com/apache/echarts/blob/master/src/core/echarts.ts#L2583-L2585
https://github.com/ecomfe/zrender/blob/86ec3b6ad44bef3699ab9b717f2511143f6f1be0/src/core/Eventful.ts#L161-L169

doc(off): update off signature

---

en/option/component/axis-common.md
zh/option/component/axis-common.md

`jitterOverlap` and `jitterMargin` were missing from the doc.

fix(jitter): add doc for jitterOverlap and jitterMargin

---

en/option/component/radar.md
zh/option/component/radar.md

This pull request adds documentation for the new `clockwise` property to the radar component in both the English and Chinese documentation. The `clockwise` property determines whether the indicator axes are laid out in a clockwise direction.
Documentation updates:
* Added a section describing the `clockwise(boolean) = false` property to `en/option/component/radar.md`, including its default value, version, a UI control example, and a description.
* Added a corresponding section for the `clockwise(boolean) = false` property to `zh/option/component/radar.md` with a translated description and matching UI control example.

feat(radar): add clockwise layout doc

---

en/option/series/bar.md
en/option/series/line.md
zh/option/series/bar.md
zh/option/series/line.md

- Add important note that stackOrder should be defined for all series with the same stack name
- Explain potential issues when stackOrder is only defined for some series
- Address feedback from PR #448 comments

doc: improve stackOrder documentation with usage notes

---

en/option-gl/component/axis3D-axis-common.md
en/option/component/axis-common.md

doc(axis): fix typo in axis.max description
"dataMax" does set the maximum value, not the minimum value

doc(axis): fix typo in axis.max description
